# Generated by Django 4.2.5 on 2023-09-21 16:47

from django.db import migrations
import django_enum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learn_python_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='domain',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'github')], default=0),
            preserve_default=False,
        ),
    ]
