# Generated by Django 4.2.5 on 2023-09-22 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn_python_server', '0002_student_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='repository',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='learn_python_server.studentrepository'),
        ),
    ]
